version: '3.7'
services:
    discord-crossposter:
        image: lulu/discord-crossposter:latest
        container_name: discord-crossposter
        hostname: discord-crossposter
        tty: true
        build:
            context: .
            target: development
        command: 'yarn start'
        volumes:
            - ./.env:/usr/app/.env
            - ./src:/usr/app/src
            - ./package.json:/usr/app/package.json
            - ./yarn.lock:/usr/app/yarn.lock
            - ./tsconfig.base.json:/usr/app/tsconfig.base.json
            - ./tsconfig.build.json:/usr/app/tsconfig.build.json
        ports:
            - '9090:9090'
        environment:
            DISCORD_CROSSPOSTER_SERVICE_METRICS_SERVER_HOST: '0.0.0.0'
            DISCORD_CROSSPOSTER_SERVICE_METRICS_SERVER_PORT: '9090'
            DISCORD_CROSSPOSTER_SERVICE_METRICS_SERVER_TRUST_PROXY: 'true'
